### ISSUE TITLE
New angular image is not included in the npm package

### ISSUE THREAD

**Issue by stefanoslig** [ng-apimock/dev-interface#519]
Hi @mdasberg 

I installed the latest version (3.3.0) in my project but for some reason it seems that the new image I added is not included in the npm package.

Do you have any idea what might have gone wrong?

![Screenshot 2023-11-30 at 21 27 00](https://github.com/ng-apimock/dev-interface/assets/6942946/a8fcffc9-0143-4717-8ecd-603d8375ea4f)

**Comment by mdasberg** [comment]
Hi @stefanoslig,

It was excluded by .npmignore. I have released 3.3.1 which should fix the issue

**Comment by stefanoslig** [comment]
Perfect!! Thank you
